name: webserver
on: [push]
jobs:  
  deploy:    
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: deploy website to aniljangir.tk
        uses: appleboy/scp-action@master
        with:
          source: "/*"
          target: "/var/www/html"
          strip_components: 1
